# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Workflows commands (::set-output): # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter

name: CI - Test Build ⚙🤖

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test_on_node:
    name: Test Build ⚙🛠

    env:
      DB_URL_TEST: ${{ secrets.DB_URL_TEST }}
      API__NEWS_TOKEN: ${{ secrets.API__NEWS_TOKEN }}
      API__FOOTBALL_TOKEN: ${{ secrets.API__FOOTBALL_TOKEN }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x, 12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} 📦
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path 🐈
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules 🧶
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules/.cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install Dependencies 🎊
        run: yarn install --frozen-lockfile --check-files

      - name: Test Build 🛠
        run: yarn build
